### ISSUE TITLE
[COMPILER BUG] Seg Fault

### ISSUE THREAD

**Issue by JakeRoggenbuck** [adamhutchings/zflat#36]
**Describe the bug**

**To Reproduce**
Seg fault when you pass a type to a function
```
~ Has the bug ~
main(): int {                         
    printf("%d\n", factorial_r(int));   
}                      

~ No bug ~
main(): int {                         
    printf("%d\n", factorial_r(x));   
}                  
```
**Expected behavior**
This should compile

**Screenshots**
![image](https://user-images.githubusercontent.com/35516367/116010144-29ec4f80-a5d2-11eb-88c7-0a8034f83c65.png)

**Desktop (please complete the following information):**
 - OS: Arch

**Comment by JakeRoggenbuck** [comment]
Thanks to @Camerooooon for finding the issue

**Comment by JakeRoggenbuck** [comment]
The following code also seg faults
```c
a(int) 
```

**Comment by adamhutchings** [comment]
Thanks @JakeRoggenbuck ! I'm looking into it. It appears that there's some out-of-bounds array access going on here, because the code runs differently at different times (including illegal instruction errors!). I'll probably have a fix for it either today or tomorrow, but we'll see.
